[manager]
cwd = { fg = "#cba6f7" }
[filetype]
rules = [
  { mime = "text/*", fg = "#cdd6f4", icon = "ğŸ“„" },
  { mime = "image/*", fg = "#cdd6f4", icon = "ğŸ“·" },
  { mime = "application/*md", fg = "#cdd6f4", icon = "ğŸ“" },
  { name = "*/", fg = "#89b4fa", icon = "ğŸ“" }
]
